### PR TITLE
Fix ETI FL value

### PR DESCRIPTION
**Pull request by basicmaster**
This should fix Opendigitalradio/dablin#37. However I currently cannot test this myself; @andimik will presumably.

### CODE REVIEW

**Comment by piratfm** [comment]
Hi, can You please check once more, I found that FL was calculated in bytes, not in words. Must be fixed in  dff901cb commit

**Comment by basicmaster** [comment]
Indeed, that commit should fix it.

**Comment by andimik** [comment]
Yes, it works :-)

**Comment by basicmaster** [comment]
OK, so no need to merge this MR.

**Pull request closed without merging**
